project: 
  type: website
  render:
    - eseal.qmd
    - References.qmd
    - Supplementary.qmd

website: 
 navbar:
    left:
      - href: eseal.qmd
        text: Manuscript
      - href: References.qmd
        text: References
      - href: Supplementary.qmd
        text: Supplementary Material
 repo-url: https://github.com/IsabellaGarfield/Test-book
 repo-actions: [issue]

format:
  html:
    theme:
      - lux
      - assets/sar_theme.scss
    toc: true

#what works: cosmo, yeti, cerulean, sandstone - I LOVE LUX